CREATE DATABASE eMart;
USE eMart;
CREATE TABLE T_ACCESS_TOKEN (
    ID BIGINT NOT NULL AUTO_INCREMENT, 
    ACCESS_TOKEN VARCHAR(100) NOT NULL,
    UPDATED_DATE TIMESTAMP, 
    CREATED_DATE TIMESTAMP, 
    CONSTRAINT PK_ACCESS_TOKEN PRIMARY KEY (ID),
    CONSTRAINT UN_ACCESS_TOKEN UNIQUE (ACCESS_TOKEN)
);
CREATE TABLE T_BUYER (
    ID INT NOT NULL AUTO_INCREMENT, 
    USERNAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    EMAILID VARCHAR(50),
    CONTACT_NUMBER CHAR(13) NOT NULL, 
    CREATED_DATE TIMESTAMP, 
    CONSTRAINT PK_BUYER_ID PRIMARY KEY (ID)
);
CREATE TABLE T_SELLER (
    ID INT NOT NULL AUTO_INCREMENT, 
    USERNAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    COMPANY VARCHAR(30) NOT NULL,
    GSTIN VARCHAR(10),
    BRIEF_COMPANY VARCHAR(255),
    POSTAL_ADDRESS VARCHAR(100),
    WEBSITE VARCHAR(30),
    EMAILID VARCHAR(50),
    CONTACT_NUMBER CHAR(13) NOT NULL, 
    CREATED_DATE TIMESTAMP, 
    CONSTRAINT PK_SELLER_ID PRIMARY KEY (ID)
);
CREATE TABLE T_CATEGORY (
    CATEGORY_ID VARCHAR(30) NOT NULL, 
    CATEGORY_NAME VARCHAR(30) NOT NULL,
    BRIEF_DETAILS VARCHAR(255),
    CONSTRAINT PK_CATEGORY_ID PRIMARY KEY (CATEGORY_ID)
);
CREATE TABLE T_SUBCATEGORY (
    SUBCATEGORY_ID VARCHAR(30) NOT NULL, 
    SUBCATEGORY_NAME VARCHAR(30) NOT NULL,
    CATEGORY_ID VARCHAR(30) NOT NULL, 
    BRIEF_DETAILS VARCHAR(255),
    GSTIN VARCHAR(10),
    CONSTRAINT PK_SUBCATEGORY_ID PRIMARY KEY (SUBCATEGORY_ID)
);
CREATE TABLE T_TRANSACTIONS (
    ID VARCHAR(30) NOT NULL, 
    BUYER_ID INT NOT NULL,
    SELLER_ID INT NOT NULL,
    TRANSACTION_TYPE VARCHAR(10),
    DATE_TIME TIMESTAMP, 
    REMARKS VARCHAR(50),
    CONSTRAINT PK_TRANSACTION_ID PRIMARY KEY (ID)
);
CREATE TABLE T_ITEMS (
    ID INT NOT NULL, 
    CATEGORY_ID VARCHAR(30) NOT NULL, 
    SUBCATEGORY_ID VARCHAR(30) NOT NULL, 
    PRICE DECIMAL(10,2) NOT NULL,
    ITEM_NAME VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(50),
    STOCK_NUMBER INT,
    REMAIN_NUMBER INT,
    REMARKS VARCHAR(50),
    CONSTRAINT PK_ITEM_ID PRIMARY KEY (ID)
);
CREATE TABLE T_PURCHASEHISTORY (
    ID INT NOT NULL, 
    BUYER_ID INT NOT NULL,
    SELLER_ID INT NOT NULL,
    TRANSACTION_ID VARCHAR(30) NOT NULL, 
    ITEM_ID INT NOT NULL, 
    NUMBER_OF_ITEMS INT, 
    DATE_TIME TIMESTAMP, 
    REMARKS VARCHAR(50),
    CONSTRAINT PK_PURCHASEHISTORY_ID PRIMARY KEY (ID)
);
CREATE TABLE T_DISCOUNTS (
    ID INT NOT NULL,
    DISCOUNT_CODE VARCHAR(50) NOT NULL, 
    PERCENTAGE DECIMAL(2,0) NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR(255),
    CONSTRAINT PK_DISCOUNTS_ID PRIMARY KEY (ID)
);